language: java
jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
addons:
  sonarcloud:
    organization: "fr1zle-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'