language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report -B
after_success:
  - mvn coveralls:report -B
